package Automation.StepDefinitions;

import Automation.PageObjects.GreatPlainsPage;
import io.cucumber.datatable.DataTable;
import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;

public class GreatPlainsStepDef extends GreatPlainsPage {

    //    Scenario: Verify user should navigate to 'Generated' tab on clicking Great Plains in Left Navigation menu
    @Given("user is on {string} page")
    public void user_is_on_great_plains_page(String greatPlainsExp) {
        verifyUserIsOnGreatPlainsPage(greatPlainsExp);
    }
    @When("user is on Generated tab by default")
    public void user_is_on_generated_tab_by_default() throws InterruptedException {
        verifyUserIsOnGeneratedTabByDefault();
    }

    //    Scenario: Verify column fields in Generated Tab in Great Plains page
    @Then("the user should be able to view the following column fields under generated tab")
    public void the_user_should_be_able_to_view_the_following_column_fields_under_generated_tab(DataTable generatedColumnFields) {
        verifyColumnFieldsUnderGeneratedTab(generatedColumnFields);
    }

    //    Scenario: Verify Search Box should display below on each column in Generated tab
    @Then("user should able to see Search Box under each column of the generated tab")
    public void user_should_able_to_see_search_box_under_each_column_of_the_generated_tab() {
        validateGeneratedColumnFieldsSearchBoxes();
    }

    //    Scenario: Verify user should navigate to 'Translated' tab in Great Plains page
    @When("user clicks on Translated tab")
    public void user_clicks_on_translated_tab() throws InterruptedException {
        clickOnTranslatedTab();
    }
    @Then("user should navigate to {string} tab")
    public void user_should_navigate_to_translated_tab(String translatedExp) {
        verifyUserIsOnTranslatedPage(translatedExp);
    }

    //    Scenario: Verify column fields in Translated Tab in Great Plains page
    @Then("the user should be able to view the following column fields under translated tab")
    public void the_user_should_be_able_to_view_the_following_column_fields_under_translated_tab(DataTable translatedColumnFields) throws InterruptedException {
        verifyColumnFieldsUnderTranslatedTab(translatedColumnFields);
    }

    //    Scenario: Verify Search Box should display below on each column in translated tab
    @Then("user should able to see Search Box under each column of the translated tab")
    public void user_should_able_to_see_search_box_under_each_column_of_the_translated_tab() {
        validateTranslatedColumnFieldsSearchBoxes();
    }

    //    Scenario: Verify user should be able to see the results of rows count next to "Generated" tab name
    @Then("user should be able to see the results of rows count next to the generated tab name")
    public void user_should_be_able_to_see_the_results_of_rows_count_next_to_the_generated_tab_name() throws InterruptedException {
        validateRowCountNextToGeneratedTabName();
    }

    //    Scenario: Verify user should be able to see the results of rows count next to "Translated" tab name
    @Then("user should be able to see the results of rows count next to the translated tab name")
    public void user_should_be_able_to_see_the_results_of_rows_count_next_to_the_translated_tab_name() throws InterruptedException {
        validateRowCountNextToTranslatedTabName();
    }

    //    Scenario: Verify user should be able to get results for applying filter on "File Name" column under generated tab
    @When("user enters generated file name record under file name search box")
    public void user_enters_generated_file_name_record_under_file_name_search_box() {
        enterFileNameRecordUnderGeneratedFileNameSearchBox();
    }
    @Then("user should be able to see generated file name record under results section")
    public void user_should_be_able_to_see_generated_file_name_record_under_results_section() {
        verifyUserAbleToViewGeneratedFileNameRecordsUnderResultsSection();
    }

    //    Scenario: Verify user should be able to get results for applying filter on "Type of Claim" column under generated tab
    @When("user enters generated type of claim under type of claim search box")
    public void user_enters_generated_type_of_claim_under_type_of_claim_search_box() {
        enterTypeOfClaimUnderGeneratedTypeOfClaimSearchBox();
    }
    @Then("user should be able to see generated type of claim under results section")
    public void user_should_be_able_to_see_generated_type_of_claim_under_results_section() {
        verifyUserAbleToViewGeneratedTypeOfClaimUnderResultsSection();
    }

    //    Scenario: Verify user should be able to get results for applying filter on "Generated By" column under generated tab
    @When("user enters mail id under generated by search box")
    public void user_enters_mail_id_under_generated_by_search_box() {
        enterMailIdUnderGeneratedBySearchBox();
    }
    @Then("user should be able to see generated mail id under results section")
    public void user_should_be_able_to_see_generated_mail_id_under_results_section() {
        verifyUserAbleToViewMailIdsUnderGeneratedByResultsSection();
    }

    //    Scenario: Verify user should be able to get results for applying filter on "Generated On" column under generated tab
    @When("user enters generated date under generated on search box")
    public void user_enters_generated_date_under_generated_on_search_box() {
        enterGeneratedDateUnderGeneratedOnSearchBox();
    }
    @Then("user should be able to see generated date under results section")
    public void user_should_be_able_to_see_generated_date_under_results_section() {
        verifyUserAbleToViewGeneratedDatesUnderGeneratedOnResultsSection();
    }

    //    Scenario: Verify user should be able to get results for applying filter on "Batches Count" column under generated tab
    @When("user enters batch count under batches count search box")
    public void user_enters_batch_count_under_batches_count_search_box() {
        enterBatchCountUnderBatchesCountSearchBox();
    }
    @Then("user should be able to see generated batch count under results section")
    public void user_should_be_able_to_see_generated_batch_count_under_results_section() {
        verifyUserAbleToViewBatchCountUnderBatchesCountResultsSection();
    }

    //    Scenario: Verify user should be able to get results for applying filter on "File Name" column under translated tab
    @When("user enters translated file name record under file name search box")
    public void user_enters_translated_file_name_record_under_file_name_search_box() {
        enterFileNameRecordUnderTranslatedFileNameSearchBox();
    }
    @Then("user should be able to see translated file name record under results section")
    public void user_should_be_able_to_see_translated_file_name_record_under_results_section() {
        verifyUserAbleToViewTranslatedFileNameRecordsUnderResultsSection();
    }

    //    Scenario: Verify user should be able to get results for applying filter on "Type of Claim" column under generated tab
    @When("user enters translated type of claim under type of claim search box")
    public void user_enters_translated_type_of_claim_under_type_of_claim_search_box() {
        enterTypeOfClaimUnderTranslatedTypeOFClaimSearchBox();
    }
    @Then("user should be able to see translated type of claim under results section")
    public void user_should_be_able_to_see_translated_type_of_claim_under_results_section() {
        verifyUserAbleToViewTranslatedTypeOfClaimUnderResultsSection();
    }

    //    Scenario: Verify user should be able to get results for applying filter on "Uploaded By" column under generated tab
    @When("user enters mail id under uploaded by search box")
    public void user_enters_mail_id_under_uploaded_by_search_box() {
        enterMailIdUnderUploadedBySearchBox();
    }
    @Then("user should be able to see uploaded mail id under results section")
    public void user_should_be_able_to_see_uploaded_mail_id_under_results_section() {
        verifyUserAbleToViewMailIdsUnderUploadedByResultsSection();
    }

    //    Scenario: Verify user should be able to get results for applying filter on "Uploaded On" column under translated tab
    @When("user enters uploaded date under uploaded on search box")
    public void user_enters_uploaded_date_under_uploaded_on_search_box() {
        enterUploadedDateUnderUploadedOnSearchBox();
    }
    @Then("user should be able to see uploaded date under results section")
    public void user_should_be_able_to_see_uploaded_date_under_results_section() {
        verifyUserAbleToViewUploadedDatesUnderUploadedOnResultsSection();
    }

    //    Scenario: Verify user should be able to get results for applying filter on "Batches Count" column under translated tab
    @When("user enters translated batch count under batches count search box")
    public void user_enters_translated_batch_count_under_batches_count_search_box() {
        enterTranslatedBatchCountUnderBatchesCountSearchBox();
    }
    @Then("user should be able to see translated batch count under results section")
    public void user_should_be_able_to_see_translated_batch_count_under_results_section() {
        verifyUserAbleToViewTranslatedBatchCountUnderBatchesCountResultsSection();
    }

}
