Feature: Great Plains

  Background:
#  DSNP Adjudicator login (Non admin)
    Given the user is in CA Login screen
    When the user enters the valid username and password and click on login button
    Given user is on "Great Plains" page

#  62830, As a tester, i want to automate view functionality of generated files tab under Great Plains main tab So that I would be able to download the Generated files
  @49281 @Sanity
  Scenario: Verify user should navigate to 'Generated' tab on clicking Great Plains in Left Navigation menu
    When user is on Generated tab by default

  @49329 @Sanity @beta
  Scenario: Verify column fields in Generated Tab in Great Plains page
    When user is on Generated tab by default
    Then the user should be able to view the following column fields under generated tab
      | File Name     |
      | Type of Claim |
      | Generated By  |
      | Generated On  |
      | Batches Count |

  @49331
  Scenario: Verify user should be able to see the results of rows count next to "Generated" tab name
    When user is on Generated tab by default
    Then user should be able to see the results of rows count next to the generated tab name

  @49342 @Sanity @beta
  Scenario: Verify Search Box should display below on each column in Generated tab
    When user is on Generated tab by default
    Then user should able to see Search Box under each column of the generated tab

  #  49344 is segregated into multiple test cases
  @49344-1
  Scenario: Verify user should be able to get results for applying filter on "File Name" column under generated tab
    When user is on Generated tab by default
    When user enters generated file name record under file name search box
    Then user should be able to see generated file name record under results section

  @49344-2
  Scenario: Verify user should be able to get results for applying filter on "Type of Claim" column under generated tab
    When user is on Generated tab by default
    When user enters generated type of claim under type of claim search box
    Then user should be able to see generated type of claim under results section

  @49344-3 @Sanity @beta
  Scenario: Verify user should be able to get results for applying filter on "Generated By" column under generated tab
    When user is on Generated tab by default
    When user enters mail id under generated by search box
    Then user should be able to see generated mail id under results section

  @49344-4
  Scenario: Verify user should be able to get results for applying filter on "Created On" column under generated tab
    When user is on Generated tab by default
    When user enters generated date under generated on search box
    Then user should be able to see generated date under results section

  @49344-5 @Sanity @beta
  Scenario: Verify user should be able to get results for applying filter on "Batches Count" column under generated tab
    When user is on Generated tab by default
    When user enters batch count under batches count search box
    Then user should be able to see generated batch count under results section


#  62831, As a tester, i want to automate view functionality of Translated files tab under Great Plains main tab So that I would be able to download the Translated files
  @49899 @Sanity
  Scenario: Verify user should navigate to 'Translated' tab in Great Plains page
    When user clicks on Translated tab
    Then user should navigate to "Translated" tab

  @49903 @Sanity @beta
  Scenario: Verify column fields in Translated Tab in Great Plains page
    And user clicks on Translated tab
    Then user should navigate to "Translated" tab
    Then the user should be able to view the following column fields under translated tab
      | File Name     |
      | Type of Claim |
      | Uploaded By   |
      | Uploaded On   |
      | Batches Count |

  @49917 @Sanity @beta
  Scenario: Verify Search Box should display below on each column in Translated tab
    When user clicks on Translated tab
    Then user should able to see Search Box under each column of the translated tab

  @49904
  Scenario: Verify user should be able to see the results of rows count next to "Translated" tab name
    When user clicks on Translated tab
    Then user should navigate to "Translated" tab
    Then user should be able to see the results of rows count next to the translated tab name

  #  49909 is segregated into multiple test cases
  @49909-1
  Scenario: Verify user should be able to get results for applying filter on "File Name" column under translated tab
    When user clicks on Translated tab
    Then user should navigate to "Translated" tab
    When user enters translated file name record under file name search box
    Then user should be able to see translated file name record under results section

  @49909-2
  Scenario: Verify user should be able to get results for applying filter on "Type of Claim" column under translated tab
    When user clicks on Translated tab
    Then user should navigate to "Translated" tab
    When user enters translated type of claim under type of claim search box
    Then user should be able to see translated type of claim under results section

  @49909-3 @Sanity @beta
  Scenario: Verify user should be able to get results for applying filter on "Uploaded By" column under translated tab
    When user clicks on Translated tab
    Then user should navigate to "Translated" tab
    When user enters mail id under uploaded by search box
    Then user should be able to see uploaded mail id under results section

  @49909-4
  Scenario: Verify user should be able to get results for applying filter on "Uploaded On" column under translated tab
    When user clicks on Translated tab
    Then user should navigate to "Translated" tab
    When user enters uploaded date under uploaded on search box
    Then user should be able to see uploaded date under results section

  @49909-5 @Sanity @beta
  Scenario: Verify user should be able to get results for applying filter on "Batches Count" column under translated tab
    When user clicks on Translated tab
    Then user should navigate to "Translated" tab
    When user enters translated batch count under batches count search box
    Then user should be able to see translated batch count under results section
